### ISSUE TITLE
Problem with building iOS samples 

### ISSUE THREAD

**Issue by MarcinKruszynski** [xamarin/net6-samples#18]
MacOS Catalina 10.15.5, XCode 11.5, .NET 5 Preview 7 (latest master):

dotnet build HelloiOS/HelloiOS.csproj

Microsoft (R) Build Engine version 16.7.0-preview-20270-03+bee129d1b for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/marcinkruszynski/Projects/net6-samples-master/HelloiOS/HelloiOS.csproj (in 2.73 min).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  HelloiOS -> /Users/marcinkruszynski/Projects/net6-samples-master/HelloiOS/bin/Debug/net5.0/ios-x64/HelloiOS.dll
  Detected signing identity:
          
    Bundle Id: com.microsoft.net5.helloios
    App Id: com.microsoft.net5.helloios

[warnings]
Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
clang : error : linker command failed with exit code 1 (use -v to see invocation) [/Users/marcinkruszynski/Projects/net6-samples-master/HelloiOS/HelloiOS.csproj]

Build FAILED.

Any idea what is a problem?  Newer Xcode 11.5 or .NET 5 version?

**Comment by rolfbjarne** [comment]
I can reproduce this, I'll come up with a fix.

**Comment by rolfbjarne** [comment]
@MarcinKruszynski A fix should be in soon, but in the meantime you can either install a preview 6, or edit the top-level global.json like this: https://github.com/xamarin/net6-samples/pull/20/files.

**Comment by MarcinKruszynski** [comment]
> @MarcinKruszynski A fix should be in soon, but in the meantime you can either install a preview 6, or edit the top-level global.json like this: https://github.com/xamarin/net6-samples/pull/20/files.

It works now. Thank you for the temporary solution.
