### ISSUE TITLE
The target platform identifier ios was not recognized

### ISSUE THREAD

**Issue by lokinfey** [xamarin/net6-samples#47]
I try to build net6-samples ,but it  shows:

/usr/local/share/dotnet/sdk/6.0.100-alpha.1.20562.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(109,5): error NETSDK1139: The target platform identifier ios was not recognized. [/Users/lokinfey/Downloads/net6-samples-main/HelloiOS/HelloiOS.csproj]

**Comment by lokinfey** [comment]
I restart my mac, eveything is okay

**Comment by jonathanpeppers** [comment]
Sometimes I have to kill all dotnet processes, and that’s probably why it fixed it. Let us know if you find other bugs, thanks.

**Comment by chucker** [comment]
I just ran into this very error, in preview 1:

```
> dotnet build HelloiOS
Microsoft (R) Build Engine version 16.9.0-preview-21103-02+198f3f262 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/usr/local/share/dotnet/sdk/6.0.100-preview.1.21103.13/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(109,5): error NETSDK1139: The target platform identifier ios was not recognized. [/Users/chucker/net6-mobile-samples/HelloiOS/HelloiOS.csproj]

Build FAILED.

/usr/local/share/dotnet/sdk/6.0.100-preview.1.21103.13/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(109,5): error NETSDK1139: The target platform identifier ios was not recognized. [/Users/chucker/net6-mobile-samples/HelloiOS/HelloiOS.csproj]
    0 Warning(s)
    1 Error(s)
```

I tried a macOS restart (though no `dotnet` processes were running), to no avail.

Should I file a separate bug?

**Comment by rolfbjarne** [comment]
@chucker you must create the `EnableWorkloadResolver.sentinel` file (as described in the README), or alternatively `export MSBuildEnableWorkloadResolver=true` for the same effect.
